### ISSUE TITLE
Prebuild v1.0 image?

### ISSUE THREAD

**Issue by VojtechVitek** [machine-learning-apps/gke-kubeconfig#1]
Hi,
I'm testing https://github.com/marketplace/actions/get-kubeconfig-file-from-gke for the first time today and so far it works great! Thank you!

The only annoying thing I noticed is that Docker Action job actually triggers docker build for this image on every single build, even if I specify `@v1.0` instead of `@latest`.

Would it be possible to prebuild this Docker image somehow/somewhere, so it can be docker pulled from a registry?

**Comment by VojtechVitek** [comment]
FYI, I've built github.com/machine-learning-apps/gke-kubeconfig Dockerfile and published the image on Docker Hub:

This is the time difference between the build times:

`uses: machine-learning-apps/gke-kubeconfig@1.0`

<img width="1074" alt="Screen Shot 2019-11-04 at 1 02 37 PM" src="https://user-images.githubusercontent.com/139342/68119734-c06f1180-ff03-11e9-879e-e5c85bdb4648.png">

`uses: docker://pressly/gke-kubeconfig:1.0`

<img width="1081" alt="Screen Shot 2019-11-04 at 1 03 54 PM" src="https://user-images.githubusercontent.com/139342/68119735-c06f1180-ff03-11e9-84fa-7d2e9f07c650.png">

**Comment by hamelsmu** [comment]
Hey @VojtechVitek I'll fix this soon, I'll create an Action in this repo that pre-builds it

**Comment by hamelsmu** [comment]
I believe this is fixed now, closing issue feel free to reopen

**Comment by VojtechVitek** [comment]
@hamelsmu Thank you.

Just FYI I believe there's a typo in the release tag name: `v.1.1` at https://github.com/machine-learning-apps/gke-kubeconfig/releases.
